### ISSUE TITLE
Double comparison not supported

### ISSUE THREAD

**Issue by Ovila98** [mjdrushton/cexprtk#12]
Hello,

I'm using cexprtk for a business project. It consists in reading some serialized data from an xml file and processing the data.
One thing that's in this xml is math formulas to represent some constraints.

For example:
`<sometag param1="50" param2="a&lt;=120" />`

Using cexprtk I can easily replace **_"a"_** with the real param2 value and evaluate the expression. Everything was working fine until I needed an expression like:
`<sometag param1="50" param2="120&lt;a&lt;480" />`

The double comparision always returns True as if the string was not parsed anymore but just casted into a boolean.
I've iterated through some tags and printed the following results:

```
130.0<=120 False
120<130.0<480 True
480<=130.0<810 True

130.0<130 False
130<=130.0<480 True
480<=130.0<810 True

130.0<200 True
200<=130.0<480 True
480<=130.0<810 True
```

As you can see my **_"a"_** value has been set to _130.0_ and every simple comparison is successful but none of the double comparisons are correct.

I can format my string to turn the double comparison into an "and" logic operation involving 2 simple comparisons to workaround but that would be a shame not to directly use this wonderful module.

Is this an actual issue with the module or am I missing something on the module's functionnality ?

**Comment by mjdrushton** [comment]
Thank you for gettting in touch. cexprtk is a python wrapper around the exprtk C++ library. It provides a way of passing expressions from python down to the library and back again. I have checked the behaviour you report against the C++ library to see if it's intrinsic behaviour or something that's being caused by the wrapper code (to check if it is an exprtk or cexprtk issue).  I have included little test program in C++ here however its output is as follows:

`
130.0 <= 120 = False
120 < 130.0 < 480 = True
480 <= 130.0 < 810 = True
130.0 < 130 = False
130 <= 130.0 < 480 = True
480 <= 130.0 < 810 = True
130.0 < 200 = True
200 <= 130.0 < 480 = True
480 <= 130.0 < 810 = True
`

```C++
#include <iostream>
#include "exprtk.hpp"
#include <string>
#include <vector>

double evaluate(const std::string& expression_string)
{
	typedef double T;
	typedef exprtk::symbol_table<T> symbol_table_t;
	typedef exprtk::expression<T>   expression_t;
	typedef exprtk::parser<T>       parser_t;

	symbol_table_t symbol_table;
	symbol_table.add_constants();

	expression_t expression;
	expression.register_symbol_table(symbol_table);

	parser_t parser;
	parser.compile(expression_string, expression);

	return expression.value();
}


int main()
{
	std::vector<std::string> expressions;
	expressions.push_back("130.0 <= 120");
	expressions.push_back("120 < 130.0 < 480");
	expressions.push_back("480 <= 130.0 < 810");
	expressions.push_back("130.0 < 130");
	expressions.push_back("130 <= 130.0 < 480");
	expressions.push_back("480 <= 130.0 < 810");
	expressions.push_back("130.0 < 200");
	expressions.push_back("200 <= 130.0 < 480");
	expressions.push_back("480 <= 130.0 < 810");

	for (std::string e : expressions)
	{
		std::cout << e << " = " << (evaluate(e) == 0 ? "False" : "True") << std::endl;
	}
}
```

As you can see this matches what you found. This suggests that this behaviour is coming from exprtk. As a result, it might be worth raising this issue with the author of exprtk https://github.com/ArashPartow/exprtk
