### ISSUE TITLE
no module named cexprtk._functionargs

### ISSUE THREAD

**Issue by MK096** [mjdrushton/cexprtk#2]
After building the exe file i get an error saying "no module named cexprtk._functionargs
![error](https://user-images.githubusercontent.com/20142735/100651735-b8cca700-3367-11eb-84f5-6e272eead1be.PNG)
"
i tried hidden-import=cexprtk._functionargs but still it did not resolve my problem.

(For frontend i am using eel which uses pythoninstaller)

**Comment by mjdrushton** [comment]
This isn't an issue with `cexprtk` but is due to pythoninstaller not detecting the import of the `_functionargs` module. You can explicitly tell `pythoninstaller` to include it in your executable by specifying `--hidden-import` option for this module e.g.:

`pythoninstaller --hidden-import=cexprtk._functionargs program.py`

The eel package allows you to pass pythoninstaller options like this:

`python -m eel script.py web --hidden-import=cexprtk._functionargs --onefile`
